<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ts5</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-01T17:40:45</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d610cfe2-6f7d-4d59-bef4-b787f6e417b6</testSuiteGuid>
   <testCaseLink>
      <guid>a725f22f-5a1e-4739-bd9f-8becb8dbc960</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc05</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d85c7a13-c45e-4ab5-bad3-41d1a049f0a7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/td01</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d85c7a13-c45e-4ab5-bad3-41d1a049f0a7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>96513ebe-7ef0-4030-b279-24597c2648da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d85c7a13-c45e-4ab5-bad3-41d1a049f0a7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fe392f33-52ad-4895-8a5c-f08e3c888a55</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
